### ISSUE TITLE
Deprecation warnings when running pitest task with Gradle 6.0

### ISSUE THREAD

**Issue by embee1981** [szpak/gradle-pitest-plugin#155] opened 2019-11-10 16:05 UTC
When running the "pitest" task with Gradle 6.0 I get the following warnings (ensure "all" warnings are show, eg via gradle.properties file with org.gradle.warning.mode=all ):

> Task :pitest
Property 'additionalClasspathFile' has conflicting type annotations declared: @Input, @OutputFile; assuming @Input. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'additionalClasspathFile' has @Input annotation used on property of type 'File'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'defaultFileForHistoryData' has @Input annotation used on property of type 'File'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'historyInputLocation' has @Input annotation used on property of type 'File'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'jvmPath' has @Input annotation used on property of type 'File'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.

**Comment by remal** [comment] 2020-02-21 14:09
@szpak Could you please fix it?

**Comment by szpak** [comment] 2020-02-21 15:36
I had a discussion with the Gradle guys about that and we didn't reach a consensus. I will try to make the second attempt to make it supported in Gradle (I would like to have that variable as both input and output - for different parts on the execution) or sort out how to solve it in the other way.

**Comment by remal** [comment] 2020-02-25 17:12
As I can see, right now only `additionalClasspathFile` property is marked as `@Input` and `@OutputFile`. I suggest making it optional and use it's value, if thу property is set, and some temporary file, if the property isn't set. The temporary file doesn't need to be presented in the task's outputs.

**Comment by szpak** [comment] 2020-02-26 10:25
> As I can see, right now only `additionalClasspathFile` property is marked as `@Input` and `@OutputFile`. I suggest making it optional and use it's value, if thу property is set, and some temporary file, if the property isn't set. The temporary file doesn't need to be presented in the task's outputs.

It the output of the task. Some other task re-use that. That was the initial idea to mark it as `@OutputFile`. Nevertheless, it is rather a rare (imagery) use-case and I will split it into 2 fields or just remove `@OutputFile`.

**Comment by szpak** [comment] 2020-02-26 10:25
Btw, I recalled why I haven't fixed those warnings back in September. It would remove the plugin compatibility with Gradle <5.6. See [here](https://github.com/gradle/gradle/issues/10953) and [there](https://discuss.gradle.org/t/regularpileproperty-vs-property-file/33074).

5.5.1 was released on Jun 28, 2019 - just a hair over half year ago which is quite sad (when it was just 3 months). Nevertheless, the world goes forward and I will make a switch.

**Comment by szpak** [comment] 2020-02-26 14:18
I have encountered https://github.com/gradle/gradle/issues/12351, but luckily Stefan provided a workaround.

@remal @embee1981 Please test the latest snapshot which should by Gradle6-related warnings.

```
buildscript {
    repositories {
        mavenCentral()
        //Needed only for SNAPSHOT versions
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
    dependencies {
        classpath 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.4.7-SNAPSHOT'
    }
}
```

**Comment by remal** [comment] 2020-02-26 17:49
This warning has been fixed, but another one occurs. I have a multi-module Gradle project.
```
The configuration :pitest was resolved without accessing the project in a safe manner.  This may happen when a configuration is resolved from a different project. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.2.1/userguide/viewing_debugging_dependencies.html#sub:resolving-unsafe-configuration-resolution-errors for more details.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:571)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1900(DefaultConfiguration.java:141)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1246)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1237)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitStructure(DefaultConfiguration.java:1233)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitStructure(DefaultConfiguration.java:489)
	at org.gradle.api.internal.file.CompositeFileCollection.visitStructure(CompositeFileCollection.java:181)
	at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:49)
	at org.gradle.internal.fingerprint.impl.AbstractFileCollectionFingerprinter.fingerprint(AbstractFileCollectionFingerprinter.java:46)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.lambda$visitInputFileProperties$1(ExecuteActionsTaskExecuter.java:324)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$fingerprintInputFiles$3(CaptureStateBeforeExecutionStep.java:192)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.visitInputFileProperties(ExecuteActionsTaskExecuter.java:322)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.fingerprintInputFiles(CaptureStateBeforeExecutionStep.java:188)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.captureExecutionState(CaptureStateBeforeExecutionStep.java:150)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$captureExecutionStateOp$1(CaptureStateBeforeExecutionStep.java:104)
	at org.gradle.internal.execution.steps.BuildOperationStep$1.call(BuildOperationStep.java:40)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.internal.execution.steps.BuildOperationStep.operation(BuildOperationStep.java:37)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.captureExecutionStateOp(CaptureStateBeforeExecutionStep.java:103)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$execute$0(CaptureStateBeforeExecutionStep.java:78)
	at java.util.Optional.map(Optional.java:215)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:78)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:192)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by szpak** [comment] 2020-02-26 18:21
Thanks for checking. It depends how you refers to that configuration. Please see this [commit](https://github.com/szpak/gradle-pitest-plugin/commit/846943cfeed5869dffa87c9d033446696556fc7e), is that your case? 
The change it not perfect, but I [asked](https://discuss.gradle.org/t/accessing-other-module-dependency-files-without-mutable-project-state-warnings/35048) about that and maybe there is some better way.

**Comment by remal** [comment] 2020-02-26 19:53
I'm afraid, I'm not sure if this commit is about my case or not. I suppose that the cause is that you use `rootProject.buildscript.configurations...`

**Comment by szpak** [comment] 2020-02-26 20:00
[That multi-module sample](https://github.com/szpak/gradle-pitest-plugin/tree/master/src/funcTest/resources/testProjects/multiproject) projects used in the functional tests doesn't generate any warnings with Gradle 6.x.
Please share share a link to you project (if available), modify that to generate warning or provide some other minimal which could be used to determine where the problem is.

**Comment by remal** [comment] 2020-02-27 11:07
I'm using `junit5` test-plugin, so I configured the root project like this:
```gradle
buildscript {
  // ...
  configurations.maybeCreate('pitest')
  dependencies {
    classpath 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.4.6'
    pitest 'org.pitest:pitest-junit5-plugin:0.8'
  }
}
```

Also I run Gradle with `org.gradle.parallel = true`.

Looks like pitest gradle plugin tries to resolve `pitest` configuration of the buildscript of the root project from subprojects.

I'm not sure why I have this issue and your test doesn't generate it, but, as I understand, Gradle doesn't like resolving configurations from other projects.

The project I'm working on is not an open-source, so I can give you the link.

**Comment by remal** [comment] 2020-02-27 11:11
To eliminate `The configuration :pitest was resolved without accessing the project in a safe manner` warning I've done this:
```gradle
configurations.maybeCreate("pitest")
dependencies {
    pitest "org.pitest:pitest-command-line"
    pitest "org.pitest:pitest-junit5-plugin"
}

tasks.pitest.configure {
    launchClasspath = project.configurations.pitest
}
```

**Comment by szpak** [comment] 2020-02-27 11:28
> Looks like pitest gradle plugin tries to resolve pitest configuration of the buildscript of the root project from subprojects.

Yes, it does. 

I'm glad you've found a workaround on that. The idea to do not use the root project for the pitest configuration is not new - #62. I plan to take a look at it. However, most likely it will not be backward compatible, so as the other - more common - warnings seem to be fixed I plan to release 1.4.7 soon.

@remal asa JUnit 5 user you might also benefit from #177.

**Comment by szpak** [comment] 2020-02-27 11:28
And thanks for getting into the problem in your project.

**Closed by szpak** 2020-02-27 11:28 UTC
Labels: gradle

**Comment by embee1981** [comment] 2020-02-29 01:10
@szpak thanks for this :-) , new version of plugin has reduced the deprecation warnings, just the one left for me (multi project setup, "The configuration :pitest was resolved without accessing the project in a safe manner.", gradle 6.2.1). Think you've got a bug open for this one though.

**Comment by szpak** [comment] 2020-02-29 23:34
Yes, #62 

Btw, do you have tests in a separate module or just like `@remal` you "just" have multiple projects?
