### ISSUE TITLE
upload latest version to plugins.gradle.org

### ISSUE THREAD

**Issue by borcherspm** [szpak/gradle-pitest-plugin#51] opened 2016-12-19 18:26 UTC
Would it be possible to upload the latest version and any future versions to the plugins.gradle.org?

https://plugins.gradle.org/plugin/info.solidsoft.pitest

The latest version available on plugins.gradle.org is 1.1.4 and 1.1.10 is missing.  It's much easier to use the new plugins syntax. 
 ```
plugins {
  id "info.solidsoft.pitest" version "1.1.10"
}
```

I have to resort to using a buildscript classpath dependency in the meantime to get it from maven central.

**Comment by szpak** [comment] 2016-12-19 21:49
You are right, however there are some technical issues. Nevertheless, I have it on my todo list.

Closing as a duplicate of #35.

**Closed by szpak** 2016-12-19 21:49 UTC
